# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
#############################################
# Multi-stage Dockerfile for MindBridge MCP  
#############################################

# Stage 1: Build
FROM node:lts-alpine as builder

WORKDIR /app

# Copy package files and install all dependencies (including devDependencies)
COPY package.json package-lock.json* ./
RUN npm install

# Copy the remaining source code
COPY . .

# Build the application
RUN npm run build

# Stage 2: Production image
FROM node:lts-alpine

WORKDIR /app

# Copy only the necessary files
COPY package.json package-lock.json* ./
RUN npm install --production

# Copy built artifacts from builder stage
COPY --from=builder /app/dist ./dist

# Command to run the MCP server
CMD [ "node", "dist/index.js" ]
